import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import { fetchTasks } from './api/hello';

export default function Home() {
  const [data, setData] = useState();

  useEffect(() => {
    fetchTasks(setData);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to {{cookiecutter.project_slug}}</h1>
        <h2>Server status:</h2>
        <p>{JSON.stringify(data)}</p>
      </main>


    </div>
  );
}
